# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec для broadcaster bot (Telegram-бот, точка входа: bot_main.py).
Режим: --onedir (папка с EXE и зависимостями).
Внешние tools/*.exe НЕ входят в сборку — лежат рядом:
- tools/yt-dlp.exe
- tools/deno.exe
и обновляются самостоятельно.
"""

block_cipher = None

a = Analysis(
    ['bot_main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('app/resources/text', 'app/resources/text'),
        ('app/config/runtime/app_config.yaml', 'app/config/runtime'),
        ('app/config/runtime/app_config.example.yaml', 'app/config/runtime'),
        ('app/config/runtime/README.config.txt', 'app/config/runtime'),
        ('app/llm/prompts/templates.yaml', 'app/llm/prompts'),
        ('secrets/README.txt', 'secrets'),
    ],
    hiddenimports=[
        # bootstrap
        'app.bootstrap.logging_config',
        'app.bootstrap.ensure_dirs',
        'app.bootstrap.cleanup',
        'app.bootstrap.preflight',
        'app.bootstrap.run_context',
        'app.bootstrap.cli',
        # paths
        'app.paths._root',
        'app.paths.project_paths',
        'app.paths.name_builder',
        'app.paths.output_naming',
        # config
        'app.config.settings',
        'app.config.app_config_loader',
        'app.config.env_reader',
        'app.config.validators',
        'app.config.template_loader',
        # core
        'app.core.constants',
        'app.core.models',
        'app.core.exceptions',
        'app.core.language',
        'app.core.language_profile',
        'app.core.language_resolver',
        'app.core.language_display',
        'app.core.branching',
        'app.core.env_flags',
        'app.core.error_summary',
        'app.core.text_utils',
        'app.core.safe_trim',
        'app.core.url_utils',
        'app.core.url_normalizer',
        'app.core.cta_detection',
        'app.core.confusables',
        'app.core.description_cleaner',
        'app.core.official_links',
        'app.core.video_title_cleanup',
        # runtime
        'app.runtime.ytdlp_updater',
        'app.runtime.deno_updater',
        'app.runtime.cookies_updater',
        'app.runtime.single_instance',
        'app.runtime.startup_banner',
        # ingest
        'app.ingest.youtube_metadata',
        # google
        'app.google.auth',
        'app.google.sheets_client',
        'app.google.docs_client',
        'app.google.drive_client',
        'app.google.api_retry',
        # llm
        'app.llm.llm_client',
        'app.llm.model_pricing',
        'app.llm.model_selection',
        'app.llm.llm_factory',
        'app.llm.llm_rate_limits',
        'app.llm.llm_usage_tracker',
        'app.llm.providers.provider_base',
        'app.llm.providers.provider_openai',
        'app.llm.models.model_identity',
        'app.llm.models.model_compatibility',
        'app.llm.merges.merge_service',
        'app.llm.merges.merge_orchestrator',
        'app.llm.merges.merge_executor',
        'app.llm.merges.merge_prompt',
        'app.llm.merges.merge_parser',
        'app.llm.merges.merge_retry',
        'app.llm.merges.merge_formatting',
        'app.llm.merges.merge_links',
        'app.llm.merges.merge_youtube',
        'app.llm.merges.merge_validation',
        'app.llm.merges.merge_validation_helpers',
        'app.llm.merges.merge_quality',
        'app.llm.merges.merge_run_summary',
        'app.llm.merges.merge_single_source',
        'app.llm.merges.merge_text_utils',
        'app.llm.merges.merge_constants',
        'app.llm.merges.quality_diagnostics',
        'app.llm.merges.quality_normalizer',
        'app.llm.merges.quality_service_lines',
        'app.llm.merges.script_mix_repair',
        # net
        'app.net.http_client',
        # media
        'app.media.image_normalizer',
        # resources
        'app.resources.resource_loader',
        'app.resources.text_catalog',
        'app.resources.heading_resolver',
        # planning
        'app.planning.batch_planner',
        'app.planning.sheet_loader',
        'app.planning.sheet_parser',
        'app.planning.slots',
        'app.planning.dedup',
        'app.planning.merge_rules',
        'app.planning.link_normalization',
        'app.planning.debug_self_checks',
        # pipeline
        'app.pipeline.batch_runner',
        'app.pipeline.branch_executor',
        'app.pipeline.slot_processing',
        'app.pipeline.daily_doc_publish',
        'app.pipeline.daily_telegram_publish',
        'app.pipeline.debug_artifacts',
        'app.pipeline.operator_notifier',
        'app.pipeline.runtime_services',
        # publish
        'app.publish.google_docs_writer',
        'app.publish.doc_header',
        'app.publish.doc_helpers',
        'app.publish.docs_preview_inserter',
        'app.publish.docs_request_builder',
        'app.publish.docs_table_helpers',
        'app.publish.docs_table_writer',
        'app.publish.header_context',
        'app.publish.inline_formatting',
        'app.publish.post_llm_sanitation',
        'app.publish.shared_helpers',
        'app.publish.telegram_batch_sender',
        'app.publish.telegram_renderer',
        'app.publish.sanitizers.description_composer',
        'app.publish.sanitizers.quality_gate',
        'app.publish.sanitizers.tail_parser',
        'app.publish.sanitizers.url_selector',
        # observability
        'app.observability.runtime_analytics',
        'app.observability.startup_summary',
        'app.observability.startup_health',
        'app.observability.final_summary',
        'app.observability.openai_usage',
        'app.observability.analytics_state',
        'app.observability.analytics_formatters',
        'app.observability.content_contract',
        # application
        'app.application.application',
        # telegram
        'app.telegram.bot_client',
        # telegram_bot
        'app.telegram_bot.bot_dispatcher',
        'app.telegram_bot.bot_handlers_info',
        'app.telegram_bot.bot_auth',
        'app.telegram_bot.group_registry',
        # modes
        'app.modes.single_runner',
        # third-party
        'dotenv',
        'aiogram',
        'aiogram.types',
        'aiogram.filters',
        'aiogram.fsm.storage.memory',
        'google.auth',
        'google.auth.transport.requests',
        'google.oauth2',
        'google.oauth2.credentials',
        'google.oauth2.service_account',
        'google_auth_oauthlib',
        'google_auth_oauthlib.flow',
        'googleapiclient',
        'googleapiclient.discovery',
        'googleapiclient.errors',
        'langdetect',
        'PIL',
        'PIL.Image',
        'pycountry',
        'tzdata',
        'openai',
        'httpx',
        'requests',
        'yaml',
        'zoneinfo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'yt_dlp',
        'pytest',
        'pyright',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='broadcaster',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='ico_code.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='broadcaster',
)
